package com.volunteerhub.community.dto.rest.response;

public enum ModerationAction {
    COMPLETE_EVENT,
    CHANGE_PARTICIPATION_STATUS,
    CREATE_POST,
    EDIT_POST,
    DELETE_POST,
    CREATE_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
    LIKE_TARGET,
    UNLIKE_TARGET,
    CREATE_EVENT,
    EDIT_EVENT,
    DELETE_EVENT,
    REGISTER_EVENT,
    UNREGISTER_EVENT,
    CREATE_USER_PROFILE,
    EDIT_USER_PROFILE,
    APPROVE_EVENT,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    BAN_USER,
    UNBAN_USER
}
